version: '3.8'

# x-common-variables: &common-variables
#   MYSQL_DATABASE: books
#   MYSQL_USER: MYSQL_USER
#   MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    env_file:
      - ./server/.env
    ports:
      - "9906:3306"
    # environment:
    #   <<: *common-variables
      # - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
  
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.local
      context: ./nginx
    ports:
      - 80:80
  
  api:
    build:
      dockerfile: Dockerfile.local
      context: "./server"
    depends_on:
      - mysql_db
    volumes:
      - type: bind
        source: ./server
        target: /app
    env_file:
      - ./server/.env
    # environment:
    #   <<: *common-variables
      # MYSQL_HOST_IP: mysql_db
  
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.local
      context: ./client
    volumes:
      - type: bind
        source: ./client
        target: /app

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8000:8080
    depends_on:
      - mysql_db
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db