version: '3.8'

services:
  mysql_db_prod:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    env_file:
      - ./server/.env
    ports:
      - "9906:3306"
  
  nginx_prod:
    depends_on:
      - api_prod
      - client_prod
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
  
  api_prod:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mysql_db_prod
    env_file:
      - ./server/.env
  
  client_prod:
    build:
      dockerfile: Dockerfile
      context: ./client
    env_file:
      - ./client/.env
    ports:
      - 3000:3000

  adminer_prod:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - mysql_db_prod
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_prod